# Generated by Django 4.1.1 on 2022-10-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
